groupId: com.lbg.mobile.sw.ios
repository: mobile-releases
nexusUrl: nexus-frc.vbp-bld.oncp.dev
apps:
  - name: store
    id: ${GITHUB_EVENT_NAME}
    artifacts:
      - classifier: 
        zip: false
        paths:
          - '**/STORE.zip'
