# This is a basic workflow to help you get started with Actions
name: My Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'ALL'
        # Define the possible options for the input parameter
        options:
         - SIT01
         - SIT02
         - NFT01
         - LUAT01
         - LUAT02
         - ALL

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to environment
        if: ${{ github.event.inputs.environment != 'ALL' }}
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment"
          # Add your commands to deploy to a specific environment here
      
      - name: Deploy to all environments
        if: ${{ github.event.inputs.environment == 'ALL' }}
        run: |
          echo "Deploying to all environments"
          # Add your commands to deploy to all environments here
          
      # Add more steps here that should run after the deployment
